### ISSUE TITLE
Question and broken w2s

### ISSUE THREAD

**Issue by ghost** [attilathedud/CoD4_Hacks#1]
I open an issue here because that's the only way I found to actually message you.

Actually, I had a few question concerning your masn source code, I had been following your step while randomly doing trial and error to learn more, ( I like to get lost ) and while I understand pretty much what you write, there's a small thing that I couldn't answer myself:

The 4 byte allocation placed in ebx on the start ( VirtualAlloc ); 
Why? and what it does? I understand virtual protect but your use of valloc and vfree is confusing me.
Isn't unprotecting and protecting back enough for the codecave hook? 

~

On a side-note I don't want to open an issue just to randomly ask a question, so i'll point toward your w2s function, the math is wrong and something is broken, ( I think it is the viewangle calculation? )

peace man

**Comment by attilathedud** [comment]
Hey man, glad you found some of it useful.

You said you already understand VirtualProtect, but I need to talk briefly about it to explain the VirtualAlloc and VirtualFree. So if we look at the [msdn entry for VirtualProtect](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366898(v=vs.85).aspx), we have the following prototype:
```c
BOOL WINAPI VirtualProtect(
  _In_  LPVOID lpAddress,
  _In_  SIZE_T dwSize,
  _In_  DWORD  flNewProtect,
  _Out_ PDWORD lpflOldProtect
);
```
The last parameter holds the old protection type of the area we are modifying. Normally we would do something like:
```c
DWORD old_prot;
VirtualProtect(0xDEADBEEF, 4, VM_WHATEVER, &old_prot);
//modify section as we wish
VirtualProtect(0xDEADBEEF, 4, old_prot, NULL);
```
But since we are in another application's memory space with the DLL, we need to request a section of memory to hold our `old_prot` variable using VirtualAlloc. Most of the VirtualAlloc's in the examples have the following form:
```asm
push 40h
push 1000h
push 4h
push 0
call VirtualAlloc
mov ebx,eax
```
Which translates into the following C code:
```c
ebx = VirtualAlloc(0, 4, MEM_COMMIT, PAGE_EXECUTE_READWRITE)
```
Now why do this? Technically we don't have to reprotect the memory, but it's good practice, and I've had more than one game crash on me due to me not reprotecting the code segment properly. Same with VirtualFree - technically we could leave that 4 bytes floating around, but that's messy. When messing around in another process, it's typically best to try and change as little as possible.

~

For the w2s, could you explain what is broken? I never implemented the y variable in my w2s function, so text displays on a static y offset of 100, but the x coordinates correspond. It's been a few years, but when I originally wrote the code I tested extensively and ensured it work. If you could point me to the problem, I could look into it more.

**Comment by ghost** [comment]
Woah, I didn't expect you to answer and definitely not that quickly! 
The information you provided has been really useful and now I understand correctly, thank man! 

As of the W2S, you stated it yourself, that missing 'y' offset, I guess it isn't a bug but simply a missing feature, thank for the clarification, it could be a nice learning experience to try and add it myself. 

Peace man!
